### ISSUE TITLE
bug ajout de sonneries

### ISSUE THREAD

**Issue by autiinpu2** [autiinpu2/timer-sonneries#15]
![image_2024-03-11_090110613](https://github.com/PardaSuperDev/DringTime/assets/153806409/fae1875a-c0a3-49c9-8f83-a5155ddbb2c0)

peu importe le nom que je met ça fait ça

**Comment by yannis300307** [comment]
Cela est normal pour l'instant, c'est que toutes les sonneries envoyées pour l'instant sont refusées par la base de donnée en attendant d'implémenter la connexion par compte de l'issue : #12
