### ISSUE TITLE
Couplage avec SkolAPI

### ISSUE THREAD

**Issue by Bijunoka** [autiinpu2/timer-sonneries#17]
Je pense que pouvoir se connecter a son compte ENT peut être utiles pour pouvoir voir seulement les sonnerie intéressantes, par exemple quand on est en physique il ne m'afficherais plus 30:28 mais 90:28 puisque je change de cours dans 1h30 et pas 30min

**Comment by yannis300307** [comment]
Je pense que cela ne sera pas possible car: 
1. SkolAPI n'existe pour l'instant que en python
2. Il n'existe pas encore de fonctionalité qui permet de le faire
3. Cela serai difficile à implémenter et il faut gérer la sécurité

Mais je suis ouvert à toute PR mais ce n'est pas la priorité pour l'instant.

Cordialement
