### ISSUE TITLE
L'horloge n'est plus à jours si le script JS n'est plus en fonction

### ISSUE THREAD

**Issue by yannis300307** [autiinpu2/timer-sonneries#30]
Cela arrive si l'on change de page

**Comment by yannis300307** [comment]
Done : 29d2ccbdc22a2895f5e4e102041efcb66c654ff5

**Comment by autiinpu2** [comment]
le bug me semble toujours actif

**Comment by yannis300307** [comment]
As tu vidé le cache et rechargé la page ?

**Comment by autiinpu2** [comment]
je sait pas c'est pas moi qui ai eu le problème
