### ISSUE TITLE
Ajouter une horloge

### ISSUE THREAD

**Issue by Bijunoka** [autiinpu2/timer-sonneries#41]
Je pense qu'il pourrait être bien d'ajouter une simple horloge qui nous donne l'heure dans les sonnerie possibles.

**Comment by yannis300307** [comment]
Serait-ce une activité ?

**Comment by racloody** [comment]
> Serait-ce une activité ?

Ca pourraît être une bonne idée

**Comment by yannis300307** [comment]
La feature est elle considérée comme implémentée ?

**Comment by yannis300307** [comment]
Par manque de réponse, je considère la feature comme faite
